package com.st6.committracker.domain;

public enum DisplacementCategory {
    MANAGER_REASSIGNED, PRODUCTION_EMERGENCY, RESOURCE_BLOCKED,
    SCOPE_CHANGE, DEPRIORITIZED, EXTERNAL_DEPENDENCY, OTHER
}
