import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { submitFeedback, getFeedback, type Vote } from '@/api/feedback.api';

interface AIAttributionProps {
  scope: string;
  cycleId: string;
}

export function AIAttribution({ scope, cycleId }: AIAttributionProps) {
  const queryClient = useQueryClient();
  const queryKey = ['feedback', scope, cycleId];

  const { data } = useQuery({
    queryKey,
    queryFn: () => getFeedback(scope, cycleId),
    enabled: Boolean(cycleId),
    staleTime: 60_000,
  });

  const mutation = useMutation({
    mutationFn: (vote: Vote) => submitFeedback(scope, cycleId, vote),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey });
    },
  });

  const currentVote = data?.vote ?? null;

  function handleVote(vote: Vote) {
    mutation.mutate(vote);
  }

  return (
    <div className="flex items-center gap-3 mt-3 pt-3 border-t border-outline-variant">
      <span className="text-xs text-muted flex items-center gap-1.5">
        <svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} aria-hidden="true">
          <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
        </svg>
        Generated by AI
      </span>
      <div className="flex items-center gap-1 ml-auto">
        <span className="text-xs text-muted mr-1">Accurate?</span>
        <button
          type="button"
          onClick={() => { handleVote('up'); }}
          disabled={mutation.isPending || !cycleId}
          className={`p-1 rounded transition-colors ${
            currentVote === 'up'
              ? 'text-accent bg-accent/10'
              : 'text-muted hover:text-on-surface hover:bg-surface-container'
          }`}
          aria-label="Thumbs up — this is accurate"
        >
          <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.228.22.442.39.624a3.04 3.04 0 002.319.97h.167a.185.185 0 00.146-.293L5.904 14.25v4.5z" />
          </svg>
        </button>
        <button
          type="button"
          onClick={() => { handleVote('down'); }}
          disabled={mutation.isPending || !cycleId}
          className={`p-1 rounded transition-colors ${
            currentVote === 'down'
              ? 'text-error bg-error/10'
              : 'text-muted hover:text-on-surface hover:bg-surface-container'
          }`}
          aria-label="Thumbs down — this is inaccurate"
        >
          <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M7.5 15h2.25m8.024-9.75c.011.05.028.1.044.15.54 1.757 1.18 3.465 2.082 4.816.485.724.326 1.674-.312 2.188A10.488 10.488 0 0116.5 14.25c0 .654-.06 1.293-.174 1.914a4.504 4.504 0 01-4.452 3.586H9.655a3.04 3.04 0 01-2.319-.97c-.17-.182-.307-.396-.39-.624v-4.5l3.022-5.757a.185.185 0 00-.146-.293h-.167a3.04 3.04 0 00-2.319.97c-.17.182-.307.396-.39.624V18.75M17.25 15.75A2.25 2.25 0 0019.5 13.5V6a2.25 2.25 0 00-2.25-2.25H18A2.25 2.25 0 0015.75 6v7.5a2.25 2.25 0 002.25 2.25h-.75z" />
          </svg>
        </button>
      </div>
    </div>
  );
}
