import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Fragment } from 'react';
import { Dialog, Transition } from '@headlessui/react';
export function ConfirmDialog({ open, onClose, onConfirm, title, description, confirmLabel = 'Confirm', cancelLabel = 'Cancel', variant = 'default', loading = false, }) {
    const confirmButtonClass = variant === 'danger'
        ? 'bg-red-600 hover:bg-red-700 focus:ring-red-500 text-white'
        : 'bg-blue-600 hover:bg-blue-700 focus:ring-blue-500 text-white';
    return (_jsx(Transition, { appear: true, show: open, as: Fragment, children: _jsxs(Dialog, { as: "div", className: "relative z-50", onClose: onClose, children: [_jsx(Transition.Child, { as: Fragment, enter: "ease-out duration-200", enterFrom: "opacity-0", enterTo: "opacity-100", leave: "ease-in duration-150", leaveFrom: "opacity-100", leaveTo: "opacity-0", children: _jsx("div", { className: "fixed inset-0 bg-black/40", "aria-hidden": "true" }) }), _jsx("div", { className: "fixed inset-0 flex items-center justify-center p-4", children: _jsx(Transition.Child, { as: Fragment, enter: "ease-out duration-200", enterFrom: "opacity-0 scale-95", enterTo: "opacity-100 scale-100", leave: "ease-in duration-150", leaveFrom: "opacity-100 scale-100", leaveTo: "opacity-0 scale-95", children: _jsxs(Dialog.Panel, { className: "w-full max-w-md rounded-lg bg-white p-6 shadow-xl", children: [_jsx(Dialog.Title, { className: "text-lg font-semibold text-gray-900", children: title }), description && (_jsx("p", { className: "mt-2 text-sm text-gray-500", children: description })), _jsxs("div", { className: "mt-6 flex justify-end gap-3", children: [_jsx("button", { type: "button", onClick: onClose, disabled: loading, className: "px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-300 disabled:opacity-50", children: cancelLabel }), _jsx("button", { type: "button", onClick: onConfirm, disabled: loading, className: `px-4 py-2 text-sm font-medium rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 ${confirmButtonClass}`, children: loading ? (_jsxs("span", { className: "flex items-center gap-2", children: [_jsx("span", { className: "w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" }), confirmLabel] })) : (confirmLabel) })] })] }) }) })] }) }));
}
