import { METRIC_DEFINITIONS } from '@/constants/metric-definitions';

export function MethodologyPage() {
  const metrics = Object.entries(METRIC_DEFINITIONS);

  return (
    <div className="max-w-[900px] mx-auto px-8 py-8">
      <h1 className="font-serif text-headline text-on-surface mb-2">Methodology &amp; Definitions</h1>
      <p className="text-body text-on-surface-variant mb-8 leading-relaxed">
        How every metric in Compass is calculated. All numbers are derived from
        commitment data entered by your team — no estimates or assumptions unless
        explicitly noted.
      </p>

      <div className="flex flex-col gap-6">
        {metrics.map(([key, def]) => (
          <div key={key} className="bg-surface-lowest rounded-sm p-5 border-l-2 border-accent">
            <h2 className="text-title font-medium text-on-surface mb-1">{def.label}</h2>
            <div className="flex items-center gap-2 mb-2">
              <span className="text-xs font-mono bg-surface-container px-2 py-0.5 rounded text-on-surface-variant">
                {def.formula}
              </span>
            </div>
            <p className="text-body text-on-surface-variant leading-relaxed">
              {def.description}
            </p>
          </div>
        ))}
      </div>

      <div className="mt-10 pt-6 border-t border-outline-variant">
        <h2 className="font-serif text-title text-on-surface mb-3">AI-Generated Content</h2>
        <p className="text-body text-on-surface-variant leading-relaxed mb-4">
          Several cards in Compass display AI-generated narratives: the Executive
          Briefing, Team Summary, Program Summary, and per-week Observatory
          narratives. These are generated by GPT-4.1-nano using only verified
          metric data as input — the AI does not have access to external data or
          make assumptions beyond what the numbers show.
        </p>
        <p className="text-body text-on-surface-variant leading-relaxed mb-4">
          Every AI-generated card includes a thumbs up/down feedback mechanism.
          If a narrative seems inaccurate or unhelpful, use the thumbs down button
          to flag it. This feedback is tracked and helps improve narrative quality.
        </p>

        <h2 className="font-serif text-title text-on-surface mb-3 mt-6">CHESS Categories</h2>
        <div className="grid grid-cols-2 gap-4 max-[640px]:grid-cols-1">
          <div className="bg-surface-lowest rounded-sm p-4">
            <h3 className="text-body font-medium text-on-surface mb-1">Strategic</h3>
            <p className="text-small text-on-surface-variant">Work that drives long-term objectives and organizational strategy.</p>
          </div>
          <div className="bg-surface-lowest rounded-sm p-4">
            <h3 className="text-body font-medium text-on-surface mb-1">Operational</h3>
            <p className="text-small text-on-surface-variant">Day-to-day execution work that keeps the business running.</p>
          </div>
          <div className="bg-surface-lowest rounded-sm p-4">
            <h3 className="text-body font-medium text-on-surface mb-1">Defensive</h3>
            <p className="text-small text-on-surface-variant">Risk mitigation, maintenance, and compliance work.</p>
          </div>
          <div className="bg-surface-lowest rounded-sm p-4">
            <h3 className="text-body font-medium text-on-surface mb-1">Capability Building</h3>
            <p className="text-small text-on-surface-variant">Growing skills, capacity, and organizational capability.</p>
          </div>
        </div>

        <h2 className="font-serif text-title text-on-surface mb-3 mt-6">Reconciliation Statuses</h2>
        <div className="grid grid-cols-2 gap-4 max-[640px]:grid-cols-1">
          <div className="bg-surface-lowest rounded-sm p-4">
            <h3 className="text-body font-medium text-on-surface mb-1">Completed</h3>
            <p className="text-small text-on-surface-variant">The commitment was fully delivered within the cycle.</p>
          </div>
          <div className="bg-surface-lowest rounded-sm p-4">
            <h3 className="text-body font-medium text-on-surface mb-1">Partially Completed</h3>
            <p className="text-small text-on-surface-variant">Some progress was made but the work was not fully finished.</p>
          </div>
          <div className="bg-surface-lowest rounded-sm p-4">
            <h3 className="text-body font-medium text-on-surface mb-1">Carried Forward</h3>
            <p className="text-small text-on-surface-variant">The commitment is automatically cloned into the next cycle for continued work.</p>
          </div>
          <div className="bg-surface-lowest rounded-sm p-4">
            <h3 className="text-body font-medium text-on-surface mb-1">Not Started / Dropped</h3>
            <p className="text-small text-on-surface-variant">The commitment was not worked on and will not be carried forward.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
